TERM=xterm-256color

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="miko"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

export WORKON_HOME="~/.virtualenvs"
source `which virtualenvwrapper.sh`

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git autojump tmux virtualenv virtualenvwrapper docker)

bindkey \^U backward-kill-line


# map caps lock to escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
if [[ -s $HOME/.rvm/scripts/rvm ]]; then source $HOME/.rvm/scripts/rvm; fi

export PATH=/opt/microchip/mplabc32/v2.01/bin:$PATH
export PATH=/opt/vagrant/bin:$PATH
export PATH=/usr/bin:$PATH     # hack to give /usr/bin priority
export PATH=$PATH:/home/mikob/tools/android-sdk-linux/tools
export PATH=$PATH:/home/mikob/tools/android-sdk-linux/platform-tools
export PATH="/opt/microchip/xc8/v1.12/bin":$PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export EDITOR=vim
export INPUTRC=/home/mikob/.inputrc
export DEV_ENV=1
export FFX_PROFILE="~/.mozilla/firefox/e0cvqqm9.Dev/"
export NODE_ENV=development

[ -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ] && source "$HOME/.oh-my-zsh/oh-my-zsh.sh"

alias rm="trash-rm"
alias wf="autossh mikob@mikob.webfactional.com"
alias opn="nemo '$pwd'"
alias fnd="find ./ -iname $@"
alias ack="ack-grep"
alias ls="ls --block-size=M --color=auto"
alias info="info --vi-keys"
alias dkrm="docker ps -aq | xargs -L 1 docker stop; docker ps -aq | xargs -L 1 docker rm"
alias dkrmi="docker images -f 'dangling=true' -q | xargs docker rmi"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cp='cp -i'
alias mv='mv -i'
alias make='make -j4'


# Miko's custom shell function
function cds() { cd "$@" && ls; }

function dksr() { docker stop "$1" && docker rm "$1"; }

# Miko's custom open ack results in vim
function ackvim() {
    ack "$@" && read;
    vim "-c bufdo /$@" $(ack -l $@);
}

[ -f "$HOME/.zshrc-custom" ] && source "$HOME/.zshrc-custom"
eval "$POST_RC"
