# timing, ~0.35s

# Source Prezto.
source "${HOME}/.zgen/zgen.zsh"

# edit command in vi mode
set -o vi

export TMUXIFIER=$HOME/.zgen/jimeh/tmuxifier-master

# IMPORTANT:
# Need to edit zgen save file manually anytime it's changed to make sure autoenv loads after python in order for
# .autoenv.zsh to work properly with workon command
if ! zgen saved; then
zgen prezto prompt theme 'miko'
zstyle ':prezto:*:*' color 'yes'

zgen prezto
zgen prezto git
zgen prezto completion
zgen prezto python
zgen prezto command-not-found
zgen prezto syntax-highlighting
zgen prezto ssh
zgen prezto tmux
# zgen prezto history-substring-search # causes issues with ctrl-y
zgen load Tarrasch/zsh-autoenv
zgen prezto autosuggestions

zgen load zsh-users/zsh-syntax-highlighting
zgen load tarruda/zsh-autosuggestions
zgen load lukechilds/zsh-nvm
zgen load jimeh/tmuxifier
zgen load junegunn/fzf shell

zgen save
fi

bindkey \^U backward-kill-line
bindkey '^R' history-incremental-search-backward
# zsh disable certain redirection warnings
setopt clobber
unsetopt histverify


# map caps lock to escape
# xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

export PATH=$PATH:$HOME/.zgen/jimeh/tmuxifier-master/bin
export PATH=/usr/bin:$PATH     # hack to give /usr/bin priority
export PATH="$HOME/tools/google_appengine/":$PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export EDITOR=nvim
export INPUTRC=$HOME/.inputrc
export DEV_ENV=1
export NODE_ENV=development
export LC_ALL=en_US.UTF-8

# Example aliases
alias rm="trash-put"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vim='nvim'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias opn="xdg-open `pwd`"
alias fnd="find ./ -iname $@"
alias ls="ls -h --color=auto"
alias info="info --vi-keys"
alias dkrm="docker ps -aqf 'status=exited' | xargs -L 1 docker rm -f"
alias dkrmi="docker images -f 'dangling=true' -q | xargs docker rmi"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cp='cp -i'
alias mv='mv -i'
alias make='make -j4'
alias grep='grep -i'
alias rsync='rsync -zav'
alias dl='docker logs -f --tail 1000'


# Miko's custom shell function
function cds() { cd "$@" && ls; }

function dksr() { docker stop "$1" && docker rm "$1"; }

function unz() { unzip "$@" && rm "$@"; }

# Miko's custom open search results in vim
function agvim() {
    ag "$@" && read;
    vim "-c bufdo /$@" $(ag -l $@);
}

vicd()
{
	local dst="$(command vifm --choose-dir -)"
	if [ -z "$dst" ]; then
		echo 'Directory picking cancelled/failed'
		return 1
	fi
	cd "$dst"
}

unset_docker()
{
	unset DOCKER_TLS_VERIFY
	unset DOCKER_HOST
	unset DOCKER_CERT_PATH
	unset DOCKER_API_VERSION
}

[ -f "$HOME/.zshrc-custom" ] && source "$HOME/.zshrc-custom"
eval "$POST_RC"


# RVM seems to be loaded quickly, so we don't need to lazy load
export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH=$PATH:$HOME/.zgen/jimeh/tmuxifier-master/bin
[ -s $HOME/.rvm/scripts/rvm ] && . "$HOME/.rvm/scripts/rvm"

# fancy file mover with substitutions
autoload -U zmv

export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# kubernetes
source <(kubectl completion zsh)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
