TERM=xterm-256color

# Source Prezto.
source "${HOME}/.zgen/zgen.zsh"

if ! zgen saved; then
zgen prezto prompt theme 'miko'
zstyle ':prezto:*:*' color 'yes'

zgen prezto
zgen prezto git
zgen prezto completion
zgen prezto python
zgen prezto command-not-found
# zgen prezto syntax-highlighting
zgen prezto ssh 
zgen prezto tmux
zgen prezto history-substring-search
# zgen prezto autosuggestions

zgen load zsh-users/zsh-syntax-highlighting
zgen load tarruda/zsh-autosuggestions

zgen save
fi

bindkey \^U backward-kill-line
# zsh disable certain redirection warnings
setopt clobber
unsetopt histverify


# map caps lock to escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

export PATH=/opt/microchip/mplabc32/v2.01/bin:$PATH
export PATH=/opt/vagrant/bin:$PATH
export PATH=/usr/bin:$PATH     # hack to give /usr/bin priority
export PATH="/opt/microchip/xc8/v1.12/bin":$PATH
export PATH="/home/mikob/tools/google_appengine/":$PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export EDITOR=vim
export INPUTRC=/home/mikob/.inputrc
export DEV_ENV=1
export FFX_PROFILE="~/.mozilla/firefox/e0cvqqm9.Dev/"
export NODE_ENV=development

# Example aliases
# alias rm="trash-rm"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias wf="autossh mikob@mikob.webfactional.com"
alias opn="xdg-open `pwd`"
alias fnd="find ./ -iname $@"
alias ack="ack-grep -i"
alias ls="ls -h --color=auto"
alias info="info --vi-keys"
alias dkrm="docker ps -aqf 'status=exited' | xargs -L 1 docker rm -f"
alias dkrmi="docker images -f 'dangling=true' -q | xargs docker rmi"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cp='cp -i'
alias mv='mv -i'
alias make='make -j4'
alias grep='grep -i'
alias rsync='rsync -zav'


# Miko's custom shell function
function cds() { cd "$@" && ls; }

function dksr() { docker stop "$1" && docker rm "$1"; }

function unz() { unzip "$@" && rm "$@"; }

# Miko's custom open ack results in vim
function ackvim() {
    ack "$@" && read;
    vim "-c bufdo /$@" $(ack -l $@);
}

[ -f "$HOME/.zshrc-custom" ] && source "$HOME/.zshrc-custom"
eval "$POST_RC"

# Lazy load nvm
export NVM_DIR="/home/mikob/.nvm"
nvm() {
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
    nvm "$@"
}

node() {
    echo 'hi'
    nvm current && node "$@"
    echo 'there'
}

# Lazy load rvm
export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
rvm() {
    if [[ -s $HOME/.rvm/scripts/rvm ]]; then source $HOME/.rvm/scripts/rvm; fi
    rvm "$@"
}
