# Miko's custom aliases
alias rm="trash-rm"
alias wf="autossh mikob@mikob.webfactional.com"
alias opn="nemo '$pwd'"
alias fnd="find ./ -iname $@"
alias ack="ack-grep"

# Miko's custom shell function
function cds() { cd "$@" && ls; }

# Miko's custom open ack results in vim
function ackvim() { 
    ack "$@" && read;
    vim "-c bufdo /$@" $(ack -l $@);
}
