# Miko's custom aliases
alias rm="trash-rm"
alias wf="ssh mikob@mikob.webfactional.com"
alias fnd="find ./ -iname $@"
alias ack="ack-grep"
alias opn="nautilus '$pwd'"

# Miko's custom shell function
function cds() { cd "$@" && ls; }
